# Generated by Django 4.1.7 on 2023-03-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sincere', models.TextField(help_text='içtenlik')),
                ('sincere_count', models.IntegerField(default=0)),
                ('reputable', models.TextField(help_text='saygınlık')),
                ('reputable_count', models.IntegerField(default=0)),
                ('powerful', models.TextField(help_text='güç')),
                ('powerful_count', models.IntegerField(default=0)),
                ('competence', models.TextField(help_text='yetkinlik')),
                ('competence_count', models.IntegerField(default=0)),
                ('excitement', models.TextField(help_text='heyecan')),
                ('excitement_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('performance', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='product_operation.performancemetric')),
            ],
        ),
    ]
