# Generated by Django 4.1.7 on 2023-03-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancemetric',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='performancemetric',
            name='excitement',
        ),
        migrations.RemoveField(
            model_name='performancemetric',
            name='powerful',
        ),
        migrations.RemoveField(
            model_name='performancemetric',
            name='reputable',
        ),
        migrations.RemoveField(
            model_name='performancemetric',
            name='sincere',
        ),
    ]
